# Generated by Django 4.2.1 on 2023-05-22 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_title', models.CharField(max_length=150, verbose_name='Заголовок')),
                ('slug', models.CharField(blank=True, max_length=150, null=True, verbose_name='URL')),
                ('content', models.TextField(max_length=15000, verbose_name='Содержимое')),
                ('preview_image', models.ImageField(blank=True, null=True, upload_to='image/', verbose_name='Изображение')),
                ('date_of_creation', models.DateTimeField(auto_now=True, verbose_name='Дата создания')),
                ('active_of_publication', models.BooleanField(default=True, verbose_name='Активный')),
            ],
            options={
                'verbose_name': 'статья',
                'verbose_name_plural': 'статьи',
                'ordering': ('article_title',),
            },
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('name',), 'verbose_name': 'продукт', 'verbose_name_plural': 'продукты'},
        ),
    ]
